sudo: required

services:
  - docker

before_install:
  - echo "Hello Docker"
#   - docker build -t dandu1008/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "Hello Docker"
#   - docker run dandu1008/react-test npm run test -- --coverage

after_success:
  - echo "Hello Docker"
  - docker build -t dandu1008/multi-client ./client
  - docker build -t dandu1008/multi-nginx ./nginx
  - docker build -t dandu1008/multi-server ./server
  - docker build -t dandu1008/multi-worker ./worker
  # Login into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push above images to DockerHub
  - docker push dandu1008/multi-client
  - docker push dandu1008/multi-nginx
  - docker push dandu1008/multi-server
  - docker push dandu1008/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker-2"
  env: "MultiDocker2-env"
  bucket_name: "elasticbeanstalk-eu-west-1-212730683172"
  bucket_path: "multi-docker-app-2"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
